name: "Size-Limit"
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@v2
      - uses: andresz1/size-limit-action@v1
        with:
          build_script: build
          package_manager: pnpm
          github_token: ${{ secrets.GITHUB_TOKEN }}
